// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoadAlertApi.Models;

#nullable disable

namespace RoadAlertApi.Migrations
{
    [DbContext(typeof(VehicleAlertsContext))]
    [Migration("20251022161218_Added_column")]
    partial class Added_column
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoadAlertApi.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CatalystFuelLevel")
                        .HasColumnType("int");

                    b.Property<int?>("CatalystFuelLevelChangePercent")
                        .HasColumnType("int");

                    b.Property<string>("ChargingConnectionStatusInfoEvent")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChargingConnectionStatusInfoEventDetail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("ChargingStatusInfoEstimatedDistanceToEmptyBatteryPack")
                        .HasColumnType("bigint");

                    b.Property<long?>("ChargingStatusInfoEstimatedDistanceToEmptyFuel")
                        .HasColumnType("bigint");

                    b.Property<long?>("ChargingStatusInfoEstimatedDistanceToEmptyGas")
                        .HasColumnType("bigint");

                    b.Property<long?>("ChargingStatusInfoEstimatedDistanceToEmptyTotal")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ChargingStatusInfoEstimatedTimeBatteryPackChargingCompleted")
                        .HasColumnType("datetime");

                    b.Property<string>("ChargingStatusInfoEvent")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ChargingStatusInfoHybridBatteryPackRemainingCharge")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CustomerVehicleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("FuelLevelFuelLevel1")
                        .HasColumnType("int");

                    b.Property<int?>("FuelLevelFuelLevel1ChangePercent")
                        .HasColumnType("int");

                    b.Property<string>("GenericTriggerType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GeofenceEventType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GeofenceMessage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GeofenceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("HrTotalVehicleDistance")
                        .HasColumnType("bigint");

                    b.Property<string>("IdlingAirProductionModulatorState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdlingAmbientAirTemperature")
                        .HasColumnType("int");

                    b.Property<int?>("IdlingCoolantTemperature")
                        .HasColumnType("int");

                    b.Property<string>("IdlingEventType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdlingRegenerationFilterState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OverspeedEventType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("OverspeedLimit")
                        .HasColumnType("float");

                    b.Property<string>("OverspeedTriggerType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("OverspeedWheelBasedSpeed")
                        .HasColumnType("float");

                    b.Property<string>("PtoAirProductionModulatorState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PtoAmbientAirTemperature")
                        .HasColumnType("int");

                    b.Property<int?>("PtoBatteryLevel")
                        .HasColumnType("int");

                    b.Property<int?>("PtoCoolantTemperature")
                        .HasColumnType("int");

                    b.Property<string>("PtoEventType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PtoId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PtoRegenerationFilterState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReceivedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("SafetyZoneDuration")
                        .HasColumnType("int");

                    b.Property<string>("SafetyZoneEventType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SafetyZoneName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SafetyZoneOverspeedingReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SafetyZoneTopSpeed")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TachoOutOfModeEventType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("TotalElectricMotorHours")
                        .HasColumnType("float");

                    b.Property<double?>("TotalEngineHours")
                        .HasColumnType("float");

                    b.Property<string>("Vin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Alerts__3214EC07CD84463D");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("RoadAlertApi.Models.Cargo", b =>
                {
                    b.Property<int?>("AlertId")
                        .HasColumnType("int");

                    b.Property<bool?>("CargoDefrostOn")
                        .HasColumnType("bit");

                    b.Property<bool?>("CargoDoorOpen")
                        .HasColumnType("bit");

                    b.Property<string>("CargoTemperatures")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("AlertId");

                    b.ToTable("Cargo", (string)null);
                });

            modelBuilder.Entity("RoadAlertApi.Models.DriverId", b =>
                {
                    b.Property<int?>("AlertId")
                        .HasColumnType("int");

                    b.Property<string>("CardIssuingMemberState")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("CardRenewalIndex")
                        .HasColumnType("int");

                    b.Property<int?>("CardReplacementIndex")
                        .HasColumnType("int");

                    b.Property<string>("DriverAuthenticationEquipment")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OemDriverIdentification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OemDriverIdentificationIdType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("TachoDriverIdentification")
                        .HasColumnType("bigint");

                    b.HasIndex("AlertId");

                    b.ToTable("DriverId", (string)null);
                });

            modelBuilder.Entity("RoadAlertApi.Models.GnssPosition", b =>
                {
                    b.Property<int?>("AlertId")
                        .HasColumnType("int");

                    b.Property<double?>("Altitude")
                        .HasColumnType("float");

                    b.Property<int?>("Heading")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime?>("PositionDateTime")
                        .HasColumnType("datetime");

                    b.Property<double?>("Speed")
                        .HasColumnType("float");

                    b.HasIndex("AlertId");

                    b.ToTable("GnssPosition", (string)null);
                });

            modelBuilder.Entity("RoadAlertApi.Models.Tpm", b =>
                {
                    b.Property<int?>("AlertId")
                        .HasColumnType("int");

                    b.Property<int?>("AxleId")
                        .HasColumnType("int");

                    b.Property<string>("BatteryStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EventType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("InformationEvent")
                        .HasColumnType("bit");

                    b.Property<string>("LeakageWarning")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("PressureActual")
                        .HasColumnType("float");

                    b.Property<double?>("PressureReference")
                        .HasColumnType("float");

                    b.Property<string>("PressureWarning")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Temperature")
                        .HasColumnType("float");

                    b.Property<string>("TemperatureStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TireLocation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("TpmActive")
                        .HasColumnType("bit");

                    b.HasIndex("AlertId");

                    b.ToTable("Tpm", (string)null);
                });

            modelBuilder.Entity("RoadAlertApi.Models.Ttm", b =>
                {
                    b.Property<int?>("AlertId")
                        .HasColumnType("int");

                    b.Property<int?>("AxleId")
                        .HasColumnType("int");

                    b.Property<string>("BatteryStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EventType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("InformationEvent")
                        .HasColumnType("bit");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("TemperatureActual")
                        .HasColumnType("float");

                    b.Property<string>("TemperatureWarning")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Test")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TireActive")
                        .HasColumnType("bit");

                    b.Property<string>("TireLocation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("AlertId");

                    b.ToTable("Ttm", (string)null);
                });

            modelBuilder.Entity("RoadAlertApi.Models.Cargo", b =>
                {
                    b.HasOne("RoadAlertApi.Models.Alert", "Alert")
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .HasConstraintName("FK__Cargo__AlertId__3C69FB99");

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("RoadAlertApi.Models.DriverId", b =>
                {
                    b.HasOne("RoadAlertApi.Models.Alert", "Alert")
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .HasConstraintName("FK__DriverId__AlertI__38996AB5");

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("RoadAlertApi.Models.GnssPosition", b =>
                {
                    b.HasOne("RoadAlertApi.Models.Alert", "Alert")
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .HasConstraintName("FK__GnssPosit__Alert__3A81B327");

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("RoadAlertApi.Models.Tpm", b =>
                {
                    b.HasOne("RoadAlertApi.Models.Alert", "Alert")
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .HasConstraintName("FK__Tpm__AlertId__3E52440B");

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("RoadAlertApi.Models.Ttm", b =>
                {
                    b.HasOne("RoadAlertApi.Models.Alert", "Alert")
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .HasConstraintName("FK__Ttm__AlertId__403A8C7D");

                    b.Navigation("Alert");
                });
#pragma warning restore 612, 618
        }
    }
}
